name: Build Handbook PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install pandoc/texlive
      run: sudo apt install pandoc texlive-xetex
    - name: Run pandoc
      run: pandoc -N -V "geometry:left=1.5cm,right=1.5cm,top=1cm,bottom=2cm" -H header.tex handbook.md --toc -o handbook.pdf
    - uses: actions/upload-artifact@v1
      with:
        name: atlantia-marshal-handbook.pdf
        path: handbook.pdf
