name: Build Handbook PDF

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install pandoc/texlive
      run: sudo apt install pandoc texlive-xetex
    - name: Run pandoc
      run: pandoc -N -V "geometry:left=1.5cm,right=1.5cm,top=1cm,bottom=2cm" handbook.md --toc -o handbook.pdf -M date="$(date '+%B %e, %Y')"
    - uses: actions/upload-artifact@v1
      with:
        name: atlantia-marshal-handbook
        path: handbook.pdf
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: draft-${{ github.sha }}
        release_name: Rules Update ${{ github.sha }}
        draft: false
        prerelease: true
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    - name: Upload PDF
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./handbook.pdf
        asset_name: atlantia-marshal-handbook.pdf
        asset_content_type: application/pdf
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
